### ISSUE TITLE
Feature extraction

### ISSUE THREAD

**Issue by chcchc97** [sqiangcao99/E2E-LOAD#2]
I have another question about the feature extraction. Because I want to apply E2E-LOAD to other datasets, so I try to extract the features by myself. As section 4 Implementation details in the supplementary of the paper, "for THUMOS’14 and TVSeries, we follow the previous works [9] by extracting video frames at 24 FPS and down-sampling the video into a series of chunks at 4 FPS as inputs".". I have resample the videos at 24 FPS and extract RGB and flow(视频帧和光流) using (https://github.com/open-mmlab/mmaction2/blob/main/tools/data/activitynet/README.md) But I don't know how to set the video chunk size to 6. How could you do that and are there any tools in mmaction2 can help to realize this step?

**Comment by sqiangcao99** [comment]
My apologies for the belated reply. E2E-LOAD directly processes raw video frames at 24FPS as input and utilizes the cfg.MODEL.CHUNK_SIZE variable within the code to set the chunk size to 6. Besides, E2E-LOAD does not use optical flow as an input.

**Comment by chcchc97** [comment]
Thank you for you reply!

**Comment by Juice-zz** [comment]
Why are the features I extracted all 1*2048 instead of frame count*2048? How can I solve this problem?

**Comment by Juice-zz** [comment]
Why are the features I extracted all 1*2048 instead of frame count*2048? How can I solve this problem?

**Comment by LittlePotatoChip** [comment]
> My apologies for the belated reply. E2E-LOAD directly processes raw video frames at 24FPS as input and utilizes the cfg.MODEL.CHUNK_SIZE variable within the code to set the chunk size to 6. Besides, E2E-LOAD does not use optical flow as an input.

Do you mean that I only need to extract the video data into 24 RGB frames per second? But why are there L labels for each video and 6L images under frames?

<img width="1008" height="356" alt="Image" src="https://github.com/user-attachments/assets/985f9a4e-f3ea-43ad-b39c-1c953403a9c7" />
