### ISSUE TITLE
about targets file

### ISSUE THREAD

**Issue by chcchc97** [sqiangcao99/E2E-LOAD#3]
I'm uncertain about how to create the targets file. Could you please describe how to create it and provide the relevant code? It would greatly assist me.
![image](https://github.com/sqiangcao99/E2E-LOAD/assets/60684460/5d963cf4-32e1-4df4-bbd2-f60489912d18)

**Comment by jayes97** [comment]
What I understood from https://github.com/amazon-science/long-short-term-transformer/issues/16#issuecomment-1314705485 this post is that L is number of frames while 22 is number of classes.
