### ISSUE TITLE
ModuleNotFoundError: No module named 'src.models.video_model_builder'

### ISSUE THREAD

**Issue by xiezhangxiang** [sqiangcao99/E2E-LOAD#4]
First of all, thank you for your work and the code provided. I encountered an issue when running your code and hope you can assist. The error message is as follows:
`Traceback (most recent call last):
  File "/E2E-LOAD/tools/run_net.py", line 9, in <module>
    from src.utils.misc import launch_job
  File "E2E-LOAD/src/utils/misc.py", line 25, in <module>
    from src.models.batchnorm_helper import SubBatchNorm3d
  File "E2E-LOAD/src/models/__init__.py", line 5, in <module>
    from .contrastive import ContrastiveModel  # noqa
  File "E2E-LOAD/src/models/contrastive.py", line 13, in <module>
    from src.models.video_model_builder import MViT
ModuleNotFoundError: No module named 'src.models.video_model_builder'`
Could you please provide the runnable code for this part? Thank you again.

**Comment by poppingshef** [comment]
I met the same problem too.
Could you please provide the runnable code for this part? Thank you very much.

**Comment by chcchc97** [comment]
Could you solve this problem? @xiezhangxiang @poppingshef

**Comment by LittlePotatoChip** [comment]
> Could you solve this problem? [@xiezhangxiang](https://github.com/xiezhangxiang) [@poppingshef](https://github.com/poppingshef)

same problem.
